//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformatiaOProductii
    {
        public int id { get; set; }
        public string Naimenovanie { get; set; }
        public string TipMateriala { get; set; }
        public int KolvoVYpokovke { get; set; }
        public string EdinIzmerenia { get; set; }
        public int KolvoNaSklade { get; set; }
        public int MinOstatok { get; set; }
        public decimal Stoimost { get; set; }
    }
}
