//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public int id { get; set; }
        public string Product { get; set; }
        public string NaimenovanieMateriala { get; set; }
        public int NKolvoManeriala { get; set; }
    }
}
