//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string NaimenovanieProductii { get; set; }
        public int Artikul { get; set; }
        public decimal MinStoimostdliaAgenta { get; set; }
        public byte[] Izobragenie { get; set; }
        public string TipProductii { get; set; }
        public int KolvoChelovekDliaProizvodstva { get; set; }
        public int NomerDliaProizvodstva { get; set; }
    }
}
